#!/bin/ash
set -e

readonly PID_FILE="/run/syslogd.pid"

[[ -e "$PID_FILE" ]] && rm -v "$PID_FILE"

if [ "$(id -u)" -eq 0 ]; then
  # drop privileges and re-execute this script unprivileged
  echo ">> dropping privileges"
  export HOME="$APP_HOME" USER="$APP_USER" LOGNAME="$APP_USER" PATH="/usr/local/bin:/bin:/usr/bin"
  exec /usr/bin/setpriv --reuid="$APP_USER" --regid="$APP_GROUP" --init-groups --inh-caps=-all "$0" "$@"
fi

# -n: stay in foreground
# -O: log to file (- is stdout)
exec /sbin/syslogd -n -O -

# vim: set ft=bash ts=2 sts=2 expandtab:

